services:
  web:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./custom_addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo_filestore:/var/lib/odoo/.local/share/Odoo/filestore
      - odoo_sessions:/var/lib/odoo/.local/share/Odoo/sessions
    user: root
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y python3-pip python3-setuptools python3-wheel &&
        pip3 install --break-system-packages qifparse &&
        mkdir -p /var/lib/odoo/.local/share/Odoo/sessions /var/lib/odoo/.local/share/Odoo/filestore &&
        chown -R odoo:odoo /var/lib/odoo &&
        chmod -R 777 /var/lib/odoo &&
        exec /entrypoint.sh odoo"
    restart: unless-stopped
    
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
  odoo_filestore:
  odoo_sessions: